# General training parameters
experiment_name: simpleCLIPTrain
seed: 42 #TODO
device: cuda  # or cpu

# Data parameters
dataset:
  name: DSEC_Night
  data_dir: ./data
  batch_size: 8
  num_workers: 8
  train_type: "ssl"

# Model parameters TODO
backbone:
  name: '' # if name is empty -> stack of the two backbone will be used
  rgb_backbone: resnet50
  event_backbone: vit_small_patch14_dinov2.lvd142m # from timm
  embed_dim: 128
  input_size: 512
  #num_classes: 10
  #dropout: 0.25

# Optimizer parameters
optimizer:
  name: Adam
  lr: 0.001
  wd: 0.0005

# Loss function parameters
loss:
  name: CLIP

# Training loop parameters
trainer:
  epochs: 50
  log_interval: 100 # steps
  val_interval: 500 # steps
  checkpoint_interval: 50 # steps
  save_folder: 

# Scheduler parameters (optional)
scheduler:
  name: ReduceLROnPlateau
  factor: 0.1
  patience: 3
  monitor: val_loss
  mode: min

# Logging parameters
logger:
  name: wandb
  project: Cross_Modality_Framework  # Replace with your wandb project name
  entity: TwoGuysOneCode
