# General training parameters
experiment_name: simpleCLIPTrain
seed: 42
device: cuda  # or cpu

# Data parameters
dataset:
  name: DSEC_Night
  data_dir: /data
  batch_size: 4
  num_workers: 4
  outputs: ["image", "BB", "labels", "img_metas"] # these mandatory for unimodal training
  bb_num_classes: 8 # according to DSEC
  train_split: "night_dataset.txt"
  val_split: "night_test_dataset.txt"

# Model parameters TODO



model:
  name: 'resnet50_yolox'
  head: 
    name: 'yolox_head' # redoundant here, but useful for clarity
    num_classes: 8
  backbone:
    name: '' # if name is empty -> stack of the two backbone will be used
    rgb_backbone: resnet50 # from timm
    pretrained: True # if not specified, it will be set to True
    pretrained_weights: #'detr_resnet50_weights.pth' # path to pretrained weights if needed
    embed_dim: 128
    input_size: 512
    output_indices: [1, 2, 3, 4] # indices of the output layers to be used
    #dropout: 0.25



# Optimizer parameters
optimizer:
  name: Adam
  lr: 0.001
  wd: 0.0005

# Loss function parameters
loss:
  name: cross_entropy

# Training loop parameters
trainer:
  epochs: 50
  log_interval: 500 # steps
  #val_interval: 500 # steps
  checkpoint_interval: 50 # steps
  save_folder: 

# Scheduler parameters (optional)
scheduler:
  name: 
  factor: 0.1
  patience: 5
  monitor: val_loss
  mode: min

# Logging parameters
logger:
  name: wandb
  project: Cross_Modality_Framework  # Replace with your wandb project name
  entity: TwoGuysOneCode
